/**
 * generated by Xtext 2.11.0
 */
package org.xtext.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import java.util.function.Consumer;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.formatting2.IHiddenRegionFormatter;
import org.eclipse.xtext.formatting2.regionaccess.ISemanticRegion;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.eclipse.xtext.xbase.lib.Procedures.Procedure1;
import org.xtext.entityDsl.Attribute;
import org.xtext.entityDsl.ComboBox;
import org.xtext.entityDsl.ComboBoxItem;
import org.xtext.entityDsl.Domainmodel;
import org.xtext.entityDsl.Entity;
import org.xtext.entityDsl.EntityDslPackage;
import org.xtext.entityDsl.RadioButton;
import org.xtext.entityDsl.RadioButtonGroup;
import org.xtext.entityDsl.Spinner;
import org.xtext.entityDsl.TextBox;
import org.xtext.entityDsl.TrackBar;
import org.xtext.services.EntityDslGrammarAccess;

@SuppressWarnings("all")
public class EntityDslFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private EntityDslGrammarAccess _entityDslGrammarAccess;
  
  protected void _format(final Domainmodel domainmodel, @Extension final IFormattableDocument document) {
    EList<Entity> _elements = domainmodel.getElements();
    for (final Entity entity : _elements) {
      {
        final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
          it.setNewLines(2);
        };
        final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
          it.oneSpace();
        };
        document.append(document.prepend(this.textRegionExtensions.regionFor(entity).keyword("entity"), _function), _function_1);
        final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
          it.oneSpace();
        };
        document.append(this.textRegionExtensions.regionFor(entity).feature(EntityDslPackage.Literals.ENTITY__NAME), _function_2);
        final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
          it.setNewLines(2);
        };
        document.append(this.textRegionExtensions.regionFor(entity).keyword("{"), _function_3);
        final Procedure1<IHiddenRegionFormatter> _function_4 = (IHiddenRegionFormatter it) -> {
          it.newLine();
        };
        document.append(this.textRegionExtensions.regionFor(entity).keyword("}"), _function_4);
        final Procedure1<IHiddenRegionFormatter> _function_5 = (IHiddenRegionFormatter it) -> {
          it.indent();
        };
        document.<ISemanticRegion, ISemanticRegion>interior(
          this.textRegionExtensions.regionFor(entity).keyword(this._entityDslGrammarAccess.getEntityAccess().getLeftCurlyBracketKeyword_2()), 
          this.textRegionExtensions.regionFor(entity).keyword(this._entityDslGrammarAccess.getEntityAccess().getRightCurlyBracketKeyword_4()), _function_5);
        document.<Entity>format(entity);
      }
    }
  }
  
  protected void _format(final Entity entity, @Extension final IFormattableDocument document) {
    EList<Attribute> _attributes = entity.getAttributes();
    for (final Attribute attribute : _attributes) {
      {
        final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
          it.oneSpace();
        };
        document.append(this.textRegionExtensions.regionFor(attribute).feature(EntityDslPackage.Literals.ATTRIBUTE__NAME), _function);
        final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
          it.oneSpace();
        };
        document.append(this.textRegionExtensions.regionFor(attribute).keyword(":"), _function_1);
        final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
          it.noSpace();
        };
        document.append(this.textRegionExtensions.regionFor(attribute).keyword("["), _function_2);
        final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
          it.oneSpace();
        };
        document.prepend(this.textRegionExtensions.regionFor(attribute).keyword(","), _function_3);
        final Procedure1<IHiddenRegionFormatter> _function_4 = (IHiddenRegionFormatter it) -> {
          it.oneSpace();
        };
        document.append(this.textRegionExtensions.regionFor(attribute).keyword(","), _function_4);
        final Procedure1<IHiddenRegionFormatter> _function_5 = (IHiddenRegionFormatter it) -> {
          it.noSpace();
        };
        document.append(this.textRegionExtensions.regionFor(attribute.getLabelText()).feature(EntityDslPackage.Literals.LABEL__TEXT), _function_5);
        final Procedure1<IHiddenRegionFormatter> _function_6 = (IHiddenRegionFormatter it) -> {
          it.noSpace();
        };
        document.append(this.textRegionExtensions.regionFor(attribute).keyword("]"), _function_6);
        final Procedure1<IHiddenRegionFormatter> _function_7 = (IHiddenRegionFormatter it) -> {
          it.newLine();
        };
        document.<Attribute>append(attribute, _function_7);
        document.<Attribute>format(attribute);
      }
    }
  }
  
  protected void _format(final TextBox textbox, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.append(this.textRegionExtensions.regionFor(textbox).feature(EntityDslPackage.Literals.TEXT_BOX__NAME), _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.append(this.textRegionExtensions.regionFor(textbox).keyword("["), _function_1);
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.prepend(this.textRegionExtensions.regionFor(textbox).keyword("("), _function_2);
    final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.append(this.textRegionExtensions.regionFor(textbox).keyword("("), _function_3);
    final Procedure1<IHiddenRegionFormatter> _function_4 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.append(this.textRegionExtensions.regionFor(textbox).feature(EntityDslPackage.Literals.TEXT_BOX__MIN_TEXT_LENGTH), _function_4);
    final Procedure1<IHiddenRegionFormatter> _function_5 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.append(this.textRegionExtensions.regionFor(textbox).keyword(","), _function_5);
    final Procedure1<IHiddenRegionFormatter> _function_6 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.append(this.textRegionExtensions.regionFor(textbox).feature(EntityDslPackage.Literals.TEXT_BOX__MAX_TEXT_LENGTH), _function_6);
    final Procedure1<IHiddenRegionFormatter> _function_7 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.append(this.textRegionExtensions.regionFor(textbox).keyword(")"), _function_7);
  }
  
  protected void _format(final ComboBox combobox, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.prepend(this.textRegionExtensions.regionFor(combobox).keyword("("), _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.append(this.textRegionExtensions.regionFor(combobox).keyword("("), _function_1);
    EList<ComboBoxItem> _items = combobox.getItems();
    for (final ComboBoxItem comboitem : _items) {
      final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
        it.oneSpace();
      };
      document.append(this.textRegionExtensions.regionFor(comboitem).feature(EntityDslPackage.Literals.COMBO_BOX_ITEM__TEXT), _function_2);
    }
    final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.append(this.textRegionExtensions.regionFor(combobox).keyword(")"), _function_3);
    final Procedure1<IHiddenRegionFormatter> _function_4 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.append(this.textRegionExtensions.regionFor(combobox).keyword("["), _function_4);
    final Procedure1<IHiddenRegionFormatter> _function_5 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.prepend(this.textRegionExtensions.regionFor(combobox).keyword("]"), _function_5);
  }
  
  protected void _format(final RadioButtonGroup radiogroup, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.prepend(this.textRegionExtensions.regionFor(radiogroup).keyword("("), _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.append(this.textRegionExtensions.regionFor(radiogroup).keyword("("), _function_1);
    EList<RadioButton> _buttons = radiogroup.getButtons();
    for (final RadioButton radioButton : _buttons) {
      final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
        it.oneSpace();
      };
      document.append(this.textRegionExtensions.regionFor(radioButton).feature(EntityDslPackage.Literals.RADIO_BUTTON__TEXT), _function_2);
    }
    final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.append(this.textRegionExtensions.regionFor(radiogroup).keyword(")"), _function_3);
    final Procedure1<IHiddenRegionFormatter> _function_4 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.append(this.textRegionExtensions.regionFor(radiogroup).keyword("["), _function_4);
    final Procedure1<IHiddenRegionFormatter> _function_5 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.prepend(this.textRegionExtensions.regionFor(radiogroup).keyword("]"), _function_5);
  }
  
  protected void _format(final Spinner spinner, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.prepend(this.textRegionExtensions.regionFor(spinner).keyword("["), _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.append(this.textRegionExtensions.regionFor(spinner).keyword("["), _function_1);
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.append(this.textRegionExtensions.regionFor(spinner).feature(EntityDslPackage.Literals.SPINNER__DEFAULT_VALUE), _function_2);
    final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.prepend(this.textRegionExtensions.regionFor(spinner).keyword("("), _function_3);
    final Procedure1<IHiddenRegionFormatter> _function_4 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.append(this.textRegionExtensions.regionFor(spinner).keyword("("), _function_4);
    final Procedure1<IHiddenRegionFormatter> _function_5 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.append(this.textRegionExtensions.regionFor(spinner).feature(EntityDslPackage.Literals.SPINNER__MINIMUM_VALUE), _function_5);
    final Procedure1<IHiddenRegionFormatter> _function_6 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.append(this.textRegionExtensions.regionFor(spinner).feature(EntityDslPackage.Literals.SPINNER__MAXIMUM_VALUE), _function_6);
    final Procedure1<IHiddenRegionFormatter> _function_7 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.append(this.textRegionExtensions.regionFor(spinner).keyword(")"), _function_7);
  }
  
  protected void _format(final TrackBar trackbar, @Extension final IFormattableDocument document) {
    final Procedure1<IHiddenRegionFormatter> _function = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.prepend(this.textRegionExtensions.regionFor(trackbar).keyword("["), _function);
    final Procedure1<IHiddenRegionFormatter> _function_1 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.append(this.textRegionExtensions.regionFor(trackbar).keyword("["), _function_1);
    final Procedure1<IHiddenRegionFormatter> _function_2 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.prepend(this.textRegionExtensions.regionFor(trackbar).keyword(this._entityDslGrammarAccess.getTrackBarAccess().getCommaKeyword_3()), _function_2);
    final Procedure1<IHiddenRegionFormatter> _function_3 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.prepend(this.textRegionExtensions.regionFor(trackbar).feature(EntityDslPackage.Literals.TRACK_BAR__DEFAULT_TICK), _function_3);
    final Procedure1<IHiddenRegionFormatter> _function_4 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.append(this.textRegionExtensions.regionFor(trackbar).feature(EntityDslPackage.Literals.TRACK_BAR__DEFAULT_TICK), _function_4);
    final Procedure1<IHiddenRegionFormatter> _function_5 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.prepend(this.textRegionExtensions.regionFor(trackbar).feature(EntityDslPackage.Literals.TRACK_BAR__INCREMENT), _function_5);
    final Procedure1<IHiddenRegionFormatter> _function_6 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.append(this.textRegionExtensions.regionFor(trackbar).feature(EntityDslPackage.Literals.TRACK_BAR__INCREMENT), _function_6);
    final Procedure1<IHiddenRegionFormatter> _function_7 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.prepend(this.textRegionExtensions.regionFor(trackbar).feature(EntityDslPackage.Literals.TRACK_BAR__DENOMINATOR), _function_7);
    final Procedure1<IHiddenRegionFormatter> _function_8 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.append(this.textRegionExtensions.regionFor(trackbar).feature(EntityDslPackage.Literals.TRACK_BAR__DENOMINATOR), _function_8);
    final Procedure1<IHiddenRegionFormatter> _function_9 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.prepend(this.textRegionExtensions.regionFor(trackbar).keyword(this._entityDslGrammarAccess.getTrackBarAccess().getLeftParenthesisKeyword_9()), _function_9);
    final Procedure1<IHiddenRegionFormatter> _function_10 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.append(this.textRegionExtensions.regionFor(trackbar).keyword(this._entityDslGrammarAccess.getTrackBarAccess().getLeftParenthesisKeyword_9()), _function_10);
    final Procedure1<IHiddenRegionFormatter> _function_11 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.append(this.textRegionExtensions.regionFor(trackbar).keyword(this._entityDslGrammarAccess.getTrackBarAccess().getLeftParenthesisKeyword_14_0()), _function_11);
    final Procedure1<IHiddenRegionFormatter> _function_12 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.append(this.textRegionExtensions.regionFor(trackbar).feature(EntityDslPackage.Literals.TRACK_BAR__MINIMUM_VALUE), _function_12);
    final Procedure1<IHiddenRegionFormatter> _function_13 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.prepend(this.textRegionExtensions.regionFor(trackbar).feature(EntityDslPackage.Literals.TRACK_BAR__MAXIMUM_VALUE), _function_13);
    final Procedure1<IHiddenRegionFormatter> _function_14 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.append(this.textRegionExtensions.regionFor(trackbar).feature(EntityDslPackage.Literals.TRACK_BAR__MAXIMUM_VALUE), _function_14);
    final Procedure1<IHiddenRegionFormatter> _function_15 = (IHiddenRegionFormatter it) -> {
      it.oneSpace();
    };
    document.append(this.textRegionExtensions.regionFor(trackbar).keyword(this._entityDslGrammarAccess.getTrackBarAccess().getRightParenthesisKeyword_13()), _function_15);
    final Consumer<ISemanticRegion> _function_16 = (ISemanticRegion it) -> {
      final Procedure1<IHiddenRegionFormatter> _function_17 = (IHiddenRegionFormatter it_1) -> {
        it_1.oneSpace();
      };
      document.append(it, _function_17);
    };
    this.textRegionExtensions.allRegionsFor(trackbar).features(EntityDslPackage.Literals.TRACK_BAR__STRING_VALUES).forEach(_function_16);
    final Procedure1<IHiddenRegionFormatter> _function_17 = (IHiddenRegionFormatter it) -> {
      it.noSpace();
    };
    document.append(this.textRegionExtensions.regionFor(trackbar).keyword(this._entityDslGrammarAccess.getTrackBarAccess().getRightParenthesisKeyword_14_2()), _function_17);
  }
  
  public void format(final Object combobox, final IFormattableDocument document) {
    if (combobox instanceof XtextResource) {
      _format((XtextResource)combobox, document);
      return;
    } else if (combobox instanceof ComboBox) {
      _format((ComboBox)combobox, document);
      return;
    } else if (combobox instanceof RadioButtonGroup) {
      _format((RadioButtonGroup)combobox, document);
      return;
    } else if (combobox instanceof Spinner) {
      _format((Spinner)combobox, document);
      return;
    } else if (combobox instanceof TrackBar) {
      _format((TrackBar)combobox, document);
      return;
    } else if (combobox instanceof Domainmodel) {
      _format((Domainmodel)combobox, document);
      return;
    } else if (combobox instanceof Entity) {
      _format((Entity)combobox, document);
      return;
    } else if (combobox instanceof TextBox) {
      _format((TextBox)combobox, document);
      return;
    } else if (combobox instanceof EObject) {
      _format((EObject)combobox, document);
      return;
    } else if (combobox == null) {
      _format((Void)null, document);
      return;
    } else if (combobox != null) {
      _format(combobox, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(combobox, document).toString());
    }
  }
}
