/*
 * generated by Xtext 2.11.0
 */
package org.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.entityDsl.ui.internal.EntityDslActivator;

public class EntityDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EntityDslActivator.getInstance().getInjector("org.xtext.EntityDsl");
	}

}
