/*
 * generated by Xtext 2.11.0
 */
package org.xtext.validation

import org.eclipse.xtext.validation.Check
import org.xtext.entityDsl.TextBox
import org.xtext.entityDsl.EntityDslPackage

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class EntityDslValidator extends AbstractEntityDslValidator {
	

	@Check
	def checkTextBoxMinimalValue(TextBox tb) {
		if (tb.minTextLength > tb.maxTextLength && tb.maxTextLength != 0 && tb.minTextLength != 0) {
			error('Text box minimal text length must be less than maximal length', 
					EntityDslPackage.Literals.TEXT_BOX__MIN_TEXT_LENGTH)
		}
	}
	
	
	
	
	
}
