/*
 * generated by Xtext 2.11.0
 */
package org.xtext.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.ide.contentassist.antlr.internal.InternalEntityDslParser;
import org.xtext.services.EntityDslGrammarAccess;

public class EntityDslParser extends AbstractContentAssistParser {

	@Inject
	private EntityDslGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalEntityDslParser createParser() {
		InternalEntityDslParser result = new InternalEntityDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getWinFormControlTypeAccess().getAlternatives(), "rule__WinFormControlType__Alternatives");
					put(grammarAccess.getBooleanAccess().getValueAlternatives_0(), "rule__Boolean__ValueAlternatives_0");
					put(grammarAccess.getDomainmodelAccess().getGroup(), "rule__Domainmodel__Group__0");
					put(grammarAccess.getEntityAccess().getGroup(), "rule__Entity__Group__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getRadioButtonGroupAccess().getGroup(), "rule__RadioButtonGroup__Group__0");
					put(grammarAccess.getTextBoxAccess().getGroup(), "rule__TextBox__Group__0");
					put(grammarAccess.getTextBoxAccess().getGroup_4(), "rule__TextBox__Group_4__0");
					put(grammarAccess.getTextBoxAccess().getGroup_5(), "rule__TextBox__Group_5__0");
					put(grammarAccess.getComboBoxAccess().getGroup(), "rule__ComboBox__Group__0");
					put(grammarAccess.getDomainmodelAccess().getApplicationNameAssignment_1(), "rule__Domainmodel__ApplicationNameAssignment_1");
					put(grammarAccess.getDomainmodelAccess().getElementsAssignment_2(), "rule__Domainmodel__ElementsAssignment_2");
					put(grammarAccess.getEntityAccess().getNameAssignment_1(), "rule__Entity__NameAssignment_1");
					put(grammarAccess.getEntityAccess().getAttributesAssignment_3(), "rule__Entity__AttributesAssignment_3");
					put(grammarAccess.getAttributeAccess().getNameAssignment_0(), "rule__Attribute__NameAssignment_0");
					put(grammarAccess.getAttributeAccess().getInputTypeAssignment_3(), "rule__Attribute__InputTypeAssignment_3");
					put(grammarAccess.getAttributeAccess().getLabelTextAssignment_5(), "rule__Attribute__LabelTextAssignment_5");
					put(grammarAccess.getLabelAccess().getTextAssignment(), "rule__Label__TextAssignment");
					put(grammarAccess.getWinFormControlTypeAccess().getControlTypeAssignment_0(), "rule__WinFormControlType__ControlTypeAssignment_0");
					put(grammarAccess.getRadioButtonGroupAccess().getNameAssignment_0(), "rule__RadioButtonGroup__NameAssignment_0");
					put(grammarAccess.getRadioButtonGroupAccess().getButtonsAssignment_2(), "rule__RadioButtonGroup__ButtonsAssignment_2");
					put(grammarAccess.getRadioButtonGroupAccess().getRequiredAssignment_6(), "rule__RadioButtonGroup__RequiredAssignment_6");
					put(grammarAccess.getRadioButtonAccess().getTextAssignment(), "rule__RadioButton__TextAssignment");
					put(grammarAccess.getCheckBoxAccess().getNameAssignment(), "rule__CheckBox__NameAssignment");
					put(grammarAccess.getTextBoxAccess().getNameAssignment_0(), "rule__TextBox__NameAssignment_0");
					put(grammarAccess.getTextBoxAccess().getRequiredAssignment_3(), "rule__TextBox__RequiredAssignment_3");
					put(grammarAccess.getTextBoxAccess().getMinTextLengthAssignment_4_1(), "rule__TextBox__MinTextLengthAssignment_4_1");
					put(grammarAccess.getTextBoxAccess().getMaxTextLengthAssignment_5_1(), "rule__TextBox__MaxTextLengthAssignment_5_1");
					put(grammarAccess.getBooleanAccess().getValueAssignment(), "rule__Boolean__ValueAssignment");
					put(grammarAccess.getComboBoxAccess().getNameAssignment_0(), "rule__ComboBox__NameAssignment_0");
					put(grammarAccess.getComboBoxAccess().getItemsAssignment_2(), "rule__ComboBox__ItemsAssignment_2");
					put(grammarAccess.getComboBoxAccess().getRequiredAssignment_6(), "rule__ComboBox__RequiredAssignment_6");
					put(grammarAccess.getComboBoxItemAccess().getTextAssignment(), "rule__ComboBoxItem__TextAssignment");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public EntityDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EntityDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
