/*
 * generated by Xtext 2.11.0
 */
package org.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class EntityDslStandaloneSetup extends EntityDslStandaloneSetupGenerated {

	def static void doSetup() {
		new EntityDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
