/**
 * generated by Xtext 2.11.0
 */
package org.xtext.entityDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Check Box</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.entityDsl.EntityDslPackage#getCheckBox()
 * @model
 * @generated
 */
public interface CheckBox extends WinFormControlType
{
} // CheckBox
