/**
 * generated by Xtext 2.11.0
 */
package org.xtext.entityDsl.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.entityDsl.Attribute;
import org.xtext.entityDsl.CheckBox;
import org.xtext.entityDsl.ComboBox;
import org.xtext.entityDsl.ComboBoxItem;
import org.xtext.entityDsl.Domainmodel;
import org.xtext.entityDsl.Entity;
import org.xtext.entityDsl.EntityDslFactory;
import org.xtext.entityDsl.EntityDslPackage;
import org.xtext.entityDsl.Label;
import org.xtext.entityDsl.RadioButton;
import org.xtext.entityDsl.RadioButtonGroup;
import org.xtext.entityDsl.TextBox;
import org.xtext.entityDsl.WinFormControlType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class EntityDslFactoryImpl extends EFactoryImpl implements EntityDslFactory
{
  /**
	 * Creates the default factory implementation.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public static EntityDslFactory init()
  {
		try {
			EntityDslFactory theEntityDslFactory = (EntityDslFactory)EPackage.Registry.INSTANCE.getEFactory(EntityDslPackage.eNS_URI);
			if (theEntityDslFactory != null) {
				return theEntityDslFactory;
			}
		}
		catch (Exception exception) {
			EcorePlugin.INSTANCE.log(exception);
		}
		return new EntityDslFactoryImpl();
	}

  /**
	 * Creates an instance of the factory.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public EntityDslFactoryImpl()
  {
		super();
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public EObject create(EClass eClass)
  {
		switch (eClass.getClassifierID()) {
			case EntityDslPackage.DOMAINMODEL: return createDomainmodel();
			case EntityDslPackage.ENTITY: return createEntity();
			case EntityDslPackage.ATTRIBUTE: return createAttribute();
			case EntityDslPackage.LABEL: return createLabel();
			case EntityDslPackage.WIN_FORM_CONTROL_TYPE: return createWinFormControlType();
			case EntityDslPackage.RADIO_BUTTON_GROUP: return createRadioButtonGroup();
			case EntityDslPackage.RADIO_BUTTON: return createRadioButton();
			case EntityDslPackage.CHECK_BOX: return createCheckBox();
			case EntityDslPackage.TEXT_BOX: return createTextBox();
			case EntityDslPackage.BOOLEAN: return createBoolean();
			case EntityDslPackage.COMBO_BOX: return createComboBox();
			case EntityDslPackage.COMBO_BOX_ITEM: return createComboBoxItem();
			default:
				throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
		}
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public Domainmodel createDomainmodel()
  {
		DomainmodelImpl domainmodel = new DomainmodelImpl();
		return domainmodel;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public Entity createEntity()
  {
		EntityImpl entity = new EntityImpl();
		return entity;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public Attribute createAttribute()
  {
		AttributeImpl attribute = new AttributeImpl();
		return attribute;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public Label createLabel()
  {
		LabelImpl label = new LabelImpl();
		return label;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public WinFormControlType createWinFormControlType()
  {
		WinFormControlTypeImpl winFormControlType = new WinFormControlTypeImpl();
		return winFormControlType;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public RadioButtonGroup createRadioButtonGroup()
  {
		RadioButtonGroupImpl radioButtonGroup = new RadioButtonGroupImpl();
		return radioButtonGroup;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public RadioButton createRadioButton()
  {
		RadioButtonImpl radioButton = new RadioButtonImpl();
		return radioButton;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public CheckBox createCheckBox()
  {
		CheckBoxImpl checkBox = new CheckBoxImpl();
		return checkBox;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public TextBox createTextBox()
  {
		TextBoxImpl textBox = new TextBoxImpl();
		return textBox;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public org.xtext.entityDsl.Boolean createBoolean()
  {
		BooleanImpl boolean_ = new BooleanImpl();
		return boolean_;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public ComboBox createComboBox()
  {
		ComboBoxImpl comboBox = new ComboBoxImpl();
		return comboBox;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public ComboBoxItem createComboBoxItem()
  {
		ComboBoxItemImpl comboBoxItem = new ComboBoxItemImpl();
		return comboBoxItem;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public EntityDslPackage getEntityDslPackage()
  {
		return (EntityDslPackage)getEPackage();
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @deprecated
	 * @generated
	 */
  @Deprecated
  public static EntityDslPackage getPackage()
  {
		return EntityDslPackage.eINSTANCE;
	}

} //EntityDslFactoryImpl
