/**
 * generated by Xtext 2.11.0
 */
package org.xtext.entityDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.entityDsl.EntityDslPackage;
import org.xtext.entityDsl.RadioButton;
import org.xtext.entityDsl.RadioButtonGroup;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Radio Button Group</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.entityDsl.impl.RadioButtonGroupImpl#getButtons <em>Buttons</em>}</li>
 *   <li>{@link org.xtext.entityDsl.impl.RadioButtonGroupImpl#getRequired <em>Required</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RadioButtonGroupImpl extends WinFormControlTypeImpl implements RadioButtonGroup
{
  /**
	 * The cached value of the '{@link #getButtons() <em>Buttons</em>}' containment reference list.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #getButtons()
	 * @generated
	 * @ordered
	 */
  protected EList<RadioButton> buttons;

  /**
	 * The cached value of the '{@link #getRequired() <em>Required</em>}' containment reference.
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @see #getRequired()
	 * @generated
	 * @ordered
	 */
  protected org.xtext.entityDsl.Boolean required;

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  protected RadioButtonGroupImpl()
  {
		super();
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  protected EClass eStaticClass()
  {
		return EntityDslPackage.Literals.RADIO_BUTTON_GROUP;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public EList<RadioButton> getButtons()
  {
		if (buttons == null) {
			buttons = new EObjectContainmentEList<RadioButton>(RadioButton.class, this, EntityDslPackage.RADIO_BUTTON_GROUP__BUTTONS);
		}
		return buttons;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public org.xtext.entityDsl.Boolean getRequired()
  {
		return required;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public NotificationChain basicSetRequired(org.xtext.entityDsl.Boolean newRequired, NotificationChain msgs)
  {
		org.xtext.entityDsl.Boolean oldRequired = required;
		required = newRequired;
		if (eNotificationRequired()) {
			ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, EntityDslPackage.RADIO_BUTTON_GROUP__REQUIRED, oldRequired, newRequired);
			if (msgs == null) msgs = notification; else msgs.add(notification);
		}
		return msgs;
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  public void setRequired(org.xtext.entityDsl.Boolean newRequired)
  {
		if (newRequired != required) {
			NotificationChain msgs = null;
			if (required != null)
				msgs = ((InternalEObject)required).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - EntityDslPackage.RADIO_BUTTON_GROUP__REQUIRED, null, msgs);
			if (newRequired != null)
				msgs = ((InternalEObject)newRequired).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - EntityDslPackage.RADIO_BUTTON_GROUP__REQUIRED, null, msgs);
			msgs = basicSetRequired(newRequired, msgs);
			if (msgs != null) msgs.dispatch();
		}
		else if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, EntityDslPackage.RADIO_BUTTON_GROUP__REQUIRED, newRequired, newRequired));
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
		switch (featureID) {
			case EntityDslPackage.RADIO_BUTTON_GROUP__BUTTONS:
				return ((InternalEList<?>)getButtons()).basicRemove(otherEnd, msgs);
			case EntityDslPackage.RADIO_BUTTON_GROUP__REQUIRED:
				return basicSetRequired(null, msgs);
		}
		return super.eInverseRemove(otherEnd, featureID, msgs);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
		switch (featureID) {
			case EntityDslPackage.RADIO_BUTTON_GROUP__BUTTONS:
				return getButtons();
			case EntityDslPackage.RADIO_BUTTON_GROUP__REQUIRED:
				return getRequired();
		}
		return super.eGet(featureID, resolve, coreType);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
		switch (featureID) {
			case EntityDslPackage.RADIO_BUTTON_GROUP__BUTTONS:
				getButtons().clear();
				getButtons().addAll((Collection<? extends RadioButton>)newValue);
				return;
			case EntityDslPackage.RADIO_BUTTON_GROUP__REQUIRED:
				setRequired((org.xtext.entityDsl.Boolean)newValue);
				return;
		}
		super.eSet(featureID, newValue);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public void eUnset(int featureID)
  {
		switch (featureID) {
			case EntityDslPackage.RADIO_BUTTON_GROUP__BUTTONS:
				getButtons().clear();
				return;
			case EntityDslPackage.RADIO_BUTTON_GROUP__REQUIRED:
				setRequired((org.xtext.entityDsl.Boolean)null);
				return;
		}
		super.eUnset(featureID);
	}

  /**
	 * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
	 * @generated
	 */
  @Override
  public boolean eIsSet(int featureID)
  {
		switch (featureID) {
			case EntityDslPackage.RADIO_BUTTON_GROUP__BUTTONS:
				return buttons != null && !buttons.isEmpty();
			case EntityDslPackage.RADIO_BUTTON_GROUP__REQUIRED:
				return required != null;
		}
		return super.eIsSet(featureID);
	}

} //RadioButtonGroupImpl
